### ISSUE TITLE
Possible typo in README?

### ISSUE THREAD

**Issue by gswirrl** [RadValentin/postcss-prefix-selector#56]
In the code sample in the section `Usage with PostCSS`,  should the line

```
return 'body.' + prefix;
```

be

```
return 'body' + prefix;
```

?

Sorry if I'm not understanding properly! V useful project btw - has just saved me a big headache :-)

**Comment by RadValentin** [comment]
@gswirrl You're correct, it's even used that way in [this test](https://github.com/RadValentin/postcss-prefix-selector/blob/master/test/test.js#L70). I'll update accordingly, thanks for the feedback!
