### ISSUE TITLE
Update Docs with postcss-loader version 4 config

### ISSUE THREAD

**Issue by ManuLintz** [RadValentin/postcss-prefix-selector#84]
I just noticed that the webpack doc isn't up to date with version 4 of postcss-loader. 

There is a breaking change in the configuration format with `postcssOptions`: https://github.com/webpack-contrib/postcss-loader/blob/master/CHANGELOG.md#-breaking-changes-1:

> PostCSS (plugins/syntax/parser/stringifier) options was moved to the postcssOptions option

I see that there is already a PR about that: https://github.com/RadValentin/postcss-prefix-selector/pull/83

By the way thanks for this plugin it was really useful to me

**Comment by RadValentin** [comment]
Happy to hear that people are still finding this useful, I've merged the PR you mentioned, hope it helps!
