### ISSUE TITLE
ignoreFiles/includeFiles accepting Regex?

### ISSUE THREAD

**Issue by mellis481** [RadValentin/postcss-prefix-selector#90]
I'm wondering if there is a reason that `ignoreFiles` and `includeFiles` are just (optional) string arrays instead of also accepting regex.  This would be helpful because if you wanted to ignore/include all eg. Ant Design CSS files you could use regex where you targeted css files that started with `antd`.  You could also not have to deal with whether a CSS file was `styles.css` or `styles.min.css`.

If this would be a desirable enhancement, I could potentially try to fork the repo and create a PR.

**Comment by mellis481** [comment]
https://github.com/RadValentin/postcss-prefix-selector/pull/91

**Comment by RadValentin** [comment]
Sounds good to me, left comments on the PR. Thanks for contributing!
