### ISSUE TITLE
Prefix css selector from third party ui-component

### ISSUE THREAD

**Issue by chiquan-hong** [RadValentin/postcss-prefix-selector#92]
Hi Guys,

this is not an issue, it's just a general question, cause i couldn't find any information about that.
In our project we are importing an third-party ui-components library. Is it possible to prefix all the css-selector from the used component library as well? Cause at the moment it seems like, its not doing that. If yes, how can i do that?

thanks for your time and best regards,

Quan

**Comment by RadValentin** [comment]
Hey @chiquan-hong, it depends on how you're loading the third party library. You'd need to find a way to run those styles through postcss. Can you give me more details on what library you're trying to load?

**Comment by chiquan-hong** [comment]
Hi Valentin,

thanks a lot for your time and the quick reply.
To be more precise, we are using our own custom ui-components library, which is published in npm.
https://www.npmjs.com/package/@axa-ch/esales-ui-components.
We import it via package.json and then use the components.
We are running postcss through rollup (see the screenshot).

![image](https://user-images.githubusercontent.com/57704956/128671439-18fcadcc-5667-4820-b688-be105218d66b.png)


Yeah it would be great if u could create an example setup :)

thanks for your time and best regards

Quan

**Comment by EduardoUmpierre** [comment]
Hi @RadValentin. I'm trying to add prefixes to my own UI library's components and I have a very similar setup as @chiquan-hong's, the only difference is that I'm using the Webpack loader.

Did you manage to achieve this behavior?

**Comment by RadValentin** [comment]
@EduardoUmpierre Unfortunately I haven't had much time to dedicate to open source lately. I have winter vacation coming up so I may look at it but I'm not making any promises, we'll see.

**Comment by saxoncameron** [comment]
> @eduardoumpierre Unfortunately I haven't had much time to dedicate to open source lately. I have winter vacation coming up so I may look at it but I'm not making any promises, we'll see.

I'm also in this boat with Vite, and installed UI library components. @RadValentin Any updates on this, or hints? Is it possible, or would it require a feature/fix in this package?

**Comment by RadValentin** [comment]
The way I see it, the prefixer will run over all the styles that are parsed using PostCSS in a project. There's no code in the plugin that determines which styles are loaded, that's all handled by the project's PostCSS config. With that in mind, there's very little I can do to address this issue. I'm closing it for now.
