### ISSUE TITLE
`Error: PostCSS plugin postcss-prefix-selector requires PostCSS 8.`

### ISSUE THREAD

**Issue by sidoruk-sv** [RadValentin/postcss-prefix-selector#94]
Starting to get such error with a minor update to postcss-prefix-selector@1.11.0.

Interesting how that happened (see that in deps, there where postcss 8 for a long time already).

**Comment by kshiw** [comment]
help me !!! 

Uncaught Error: Module build failed (from ./node_modules/_svg-sprite-loader@6.0.9@svg-sprite-loader/lib/loader.js):
Error: [object Object] is not a PostCSS plugin

node_modules\_postcss@5.2.18@postcss\lib\processor.js:145:15

`if ((typeof i === 'undefined' ? 'undefined' : _typeof(i)) === 'object' && Array.isArray(i.plugins)) {
    normalized = normalized.concat(i.plugins);
  } else if (typeof i === 'function') {
    normalized.push(i);
  } else if ((typeof i === 'undefined' ? 'undefined' : _typeof(i)) === 'object' && (i.parse || i.stringify)) {
    throw new Error('PostCSS syntaxes cannot be used as plugins. ' + 'Instead, please use one of the ' + 'syntax/parser/stringifier options as ' + 'outlined in your PostCSS ' + 'runner documentation.');
  } else {
    // ERROR: i: { postcssPlugin: 'postcss-prefix-selector', Rule: [Function: Rule] }
    throw new Error(i + ' is not a PostCSS plugin');
  }`

An urgent fix is required. Thank you

**Comment by kshiw** [comment]
help me !!!

Uncaught Error: Module build failed (from ./node_modules/_svg-sprite-loader@6.0.9@svg-sprite-loader/lib/loader.js):
Error: [object Object] is not a PostCSS plugin

node_modules_postcss@5.2.18@postcss\lib\processor.js:145:15
`
if ((typeof i === 'undefined' ? 'undefined' : _typeof(i)) === 'object' && Array.isArray(i.plugins)) {
  normalized = normalized.concat(i.plugins);
} else if (typeof i === 'function') {
  normalized.push(i);
} else if ((typeof i === 'undefined' ? 'undefined' : _typeof(i)) === 'object' && (i.parse || i.stringify)) {
  throw new Error('PostCSS syntaxes cannot be used as plugins. ' + 'Instead, please use one of the ' + 'syntax/parser/stringifier options as ' + 'outlined in your PostCSS ' + 'runner documentation.');
} else {
  // ERROR: i: { postcssPlugin: 'postcss-prefix-selector', Rule: [Function: Rule] }
  throw new Error(i + ' is not a PostCSS plugin');
}
`

An urgent fix is required. Thank you

**Comment by RadValentin** [comment]
@kshiw @sidoruk-sv Please try to npm install again. Version `1.11.0` contained a breaking change, I published a new version `1.12.0` that fixes this.

**Comment by danielweck** [comment]
Ah, maybe this will fix this:
https://github.com/JetBrains/svg-sprite-loader/issues/469
...checking

**Comment by RadValentin** [comment]
Looks like everything went back to normal so I'm closing this one. Thanks for reporting it!

**Comment by sidoruk-sv** [comment]
@RadValentin indeed, all is working now.

Thank you for lightning fast hotfix!)
